matrix:
    include:
        - os: osx
          osx_image: xcode61
          language: objective-c
        - os: linux
          sudo: required
          dist: trusty
          env: PIP=pip
          language: cpp
          compiler: gcc
          addons:
            apt:
                packages:
                    - libusb-1.0
                    - libboost-all-dev
      
before_install:
- if [[ ${TRAVIS_OS_NAME} == linux ]]; then sudo apt-get install libudev-dev ; fi
- if [[ ${TRAVIS_OS_NAME} == linux ]]; then sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty ;fi
- if [[ ${TRAVIS_OS_NAME} == linux ]]; then sudo apt-get update -qq ;fi

- if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew update 2>&1 > /dev/null ; fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew unlink libusb ; fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/cb21e9ac30e47e3ea161c4247a6397967f83c83f/Formula/libusb.rb --universal; fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew install qt5 2>&1 > /dev/null ; fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew link qt5 --force ; fi

install: 
- if [[ ${TRAVIS_OS_NAME} == linux ]]; then sudo apt-get -y install qt553d qt55base qt55connectivity qt55declarative qt55graphicaleffects qt55imageformats qt55quick1 qt55quickcontrols qt55script qt55tools   ;fi


before_script:

- git clone https://github.com/analogdevicesinc/libsmu.git
- cd libsmu
- mkdir build && cd build && cmake -DBUILD_PYTHON=OFF -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
- make
- sudo make install
- cd ../..
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then /usr/local/opt/qt5/bin/qmake ; fi
- if [[ ${TRAVIS_OS_NAME} == linux ]]; then source /opt/qt55/bin/qt55-env.sh; /opt/qt55/bin/qmake; fi

script:
- make
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then ls libsmu/build/src ;fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then /usr/local/opt/qt5/bin/macdeployqt pixelpulse2.app -always-overwrite -verbose=2 -qmldir=qml ;fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then curl -o /tmp/macdeployqtfix.py https://raw.githubusercontent.com/aurelien-rainone/macdeployqtfix/master/macdeployqtfix.py ;fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then python /tmp/macdeployqtfix.py ./pixelpulse2.app/Contents/MacOS/pixelpulse2 /usr/local/Cellar/qt5/5.5.0_1/ ;fi

- if [[ ${TRAVIS_OS_NAME} == osx ]]; then cp libsmu/build/src/libsmu.1.dylib pixelpulse2.app/Contents/Frameworks/ ;fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then otool -L libsmu/build/src/libsmu.1.dylib ;fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then sudo install_name_tool -id libsmu.1.dylib pixelpulse2.app/Contents/Frameworks/libsmu.1.dylib ;fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then sudo install_name_tool -change @rpath/libsmu.1.dylib @executable_path/../Frameworks/libsmu.1.dylib pixelpulse2.app/Contents/MacOS/Pixelpulse2 ;fi

- if [[ ${TRAVIS_OS_NAME} == osx ]]; then otool -L pixelpulse2.app/Contents/MacOS/Pixelpulse2 ;fi

- if [[ ${TRAVIS_OS_NAME} == osx ]]; then /usr/local/opt/qt5/bin/macdeployqt pixelpulse2.app -dmg -no-plugins ;fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then mkdir deploy ;fi
- if [[ ${TRAVIS_OS_NAME} == osx ]]; then cp pixelpulse2.dmg deploy ;fi


deploy:
  provider: s3
  access_key_id: AKIAJIUMJWTHBLSLXXPA
  secret_access_key:
    secure: OLYC1jXlh0sO+4rCJFci6AnsMCl4BQpiUCC6ndExCpRdJdHeHa7AmK7VqYEWp2esD+4oh+aq+wBKA7ZpKzWIbpDffvCFfGvph8nCnUhXpfy5bRG2nsKU4NbcwYy8vd+xzY/EY5neTqWwMbbsL7L+baqs4GGv9mHzKRhCPycOW+c=
  bucket: pixelpulse2nightly
  skip_cleanup: true
  local_dir: deploy
  acl: public_read
  on:
    condition: "${TRAVIS_OS_NAME} == osx"
    repo: analogdevicesinc/Pixelpulse2
    all_branches: true