os: osx
osx_image: xcode61
language: objective-c
before_install:
- brew update 2>&1 > /dev/null
- brew install --build-from-source libusb 2>&1 > /dev/null
- brew install qt5 2>&1 > /dev/null
- brew linkapps qt5
before_script: /usr/local/opt/qt5/bin/qmake
script: 
- make
- /usr/local/opt/qt5/bin/macdeployqt pixelpulse2.app -dmg -always-overwrite -verbose=2 -qmldir=qml
- curl -o /tmp/macdeployqtfix.py https://raw.githubusercontent.com/aurelien-rainone/macdeployqtfix/master/macdeployqtfix.py
- python /tmp/macdeployqtfix.py /Volumes/pixelpulse2/pixelpulse2.app/Contents/MacOS/pixelpulse2 /usr/local/Cellar/qt5/5.5.0/
- mkdir deploy
- cp pixelpulse2.dmg deploy
deploy:
  provider: s3
  access_key_id: AKIAIQOIHEBDCDW7SGFA
  secret_access_key:
    secure: IsTspMVYrpXM7ZdETjq+2gHXixQU8NuvVxRXEJuYQgH19FJpWots+jnCufcAUramn32/ISPMCzqtRAHCsG5AicftolruHlrQlFxuQKLK6jGoEliv+1vHsymgTYA7ZmM1CebVxW2mNYPs1oSg9wEeCznpwSwhuWRnuBd2YHvFSWs=
  bucket: pixelpulse2nightly
  skip_cleanup: true
  local_dir: deploy
  acl: public_read
  on:
    repo: analogdevicesinc/Pixelpulse2
    all_branches: true
