os: osx

osx_image: xcode61

language: objective-c 

before_install:
 - brew update
 - brew install --build-from-source libusb
 - brew install qt5
 - brew linkapps qt5

before_script: /usr/local/opt/qt5/bin/qmake
script: make

after_script:
 - /usr/local/opt/qt5/binmacdeployqt pixelpulse2.app -dmg -always-overwrite -verbose=2 -qmldir=qml
