os: osx
osx_image: xcode61
language: objective-c
before_install:
- brew update 2>&1 > /dev/null
- brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/cb21e9ac30e47e3ea161c4247a6397967f83c83f/Formula/libusb.rb --universal;
- brew install qt5 2>&1 > /dev/null
- pip install cython
- brew link qt5 --force
before_script: 
- git clone https://github.com/analogdevicesinc/libsmu.git
- cd libsmu
- git checkout rework
- mkdir build && cd build && cmake -DBUILD_PYTHON=OFF -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
- make
- sudo make install
- cd ../..
- /usr/local/opt/qt5/bin/qmake
script:
- make
- /usr/local/opt/qt5/bin/macdeployqt pixelpulse2.app -always-overwrite -verbose=2 -qmldir=qml
- curl -o /tmp/macdeployqtfix.py https://raw.githubusercontent.com/aurelien-rainone/macdeployqtfix/master/macdeployqtfix.py
- python /tmp/macdeployqtfix.py ./pixelpulse2.app/Contents/MacOS/pixelpulse2 /usr/local/Cellar/qt5/5.5.0_1/
- /usr/local/opt/qt5/bin/macdeployqt pixelpulse2.app -dmg -no-plugins
- mkdir deploy
- cp pixelpulse2.dmg deploy
deploy:
  provider: s3
  access_key_id: AKIAJIUMJWTHBLSLXXPA
  secret_access_key:
    secure: OLYC1jXlh0sO+4rCJFci6AnsMCl4BQpiUCC6ndExCpRdJdHeHa7AmK7VqYEWp2esD+4oh+aq+wBKA7ZpKzWIbpDffvCFfGvph8nCnUhXpfy5bRG2nsKU4NbcwYy8vd+xzY/EY5neTqWwMbbsL7L+baqs4GGv9mHzKRhCPycOW+c=
  bucket: pixelpulse2nightly
  skip_cleanup: true
  local_dir: deploy
  acl: public_read
  on:
    repo: analogdevicesinc/Pixelpulse2
    all_branches: true
