os: Visual Studio 2015

install:
  # update libsmu submodule
  - git submodule update --init --recursive

  # libusb patched for windows hotplug support
  - git clone https://github.com/analogdevicesinc/libusb.git "C:\libusb"

build_script:
  - ps: $env:Pixelpulse2BuildDate=get-date -format "yyyy-MM-dd"
  - ps: $env:Pixelpulse2GitCommit=git describe --always --tags --abbrev

  # build our own libusb version with hotplug support until upstream merges related patches
  - ps: pushd "C:\libusb"
  - git checkout hotplug
  - msbuild msvc\libusb_2015.sln /p:Platform=Win32 /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild msvc\libusb_2015.sln /p:Platform=x64 /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: popd

  - mkdir c:\projects\pixelpulse2\32
  - cd c:\projects\pixelpulse2\32
  - C:\Qt\5.6\msvc2015\bin\qmake "CONFIG+=release" "BUILD_DATE=%Pixelpulse2BuildDate%" "GIT_COMMIT=%Pixelpulse2GitCommit%" -spec win32-msvc2015 -tp vc "LIBUSB_LIBRARY = C:\libusb\Win32\Release\dll\libusb-1.0.lib" "LIBUSB_INCLUDE_PATH = C:\libusb\libusb" ..\pixelpulse2.pro
  - msbuild pixelpulse2.vcxproj /p:Platform=Win32 /p:Configuration=Release

  - mkdir c:\projects\pixelpulse2\64
  - cd c:\projects\pixelpulse2\64
  - C:\Qt\5.6\msvc2015_64\bin\qmake "CONFIG+=release" "BUILD_DATE=%Pixelpulse2BuildDate%" "GIT_COMMIT=%Pixelpulse2GitCommit%" -spec win32-msvc2015 -tp vc "LIBUSB_LIBRARY = C:\libusb\x64\Release\dll\libusb-1.0.lib" "LIBUSB_INCLUDE_PATH = C:\libusb\libusb" ..\pixelpulse2.pro
  - msbuild pixelpulse2.vcxproj /p:Platform=x64 /p:Configuration=Release

after_build:
- ps: |
    cd c:\projects\pixelpulse2\32\release
    C:\Qt\5.6\msvc2015\bin\windeployqt pixelpulse2.exe --qmldir ..\..\qml  --dir distrib
    cp C:\OpenSSL-Win32\libeay32.dll distrib
    cp C:\OpenSSL-Win32\libssl32.dll distrib
    cp C:\OpenSSL-Win32\ssleay32.dll distrib
    cp C:\OpenSSL-Win32\bin\msvcr120.dll distrib
    cp C:\libusb\Win32\Release\dll\libusb-1.0.dll distrib
    7z a -y pixelpulse2_exe_r_32.zip pixelpulse2.exe
    7z a -y distrib_r_32.zip distrib

    appveyor PushArtifact pixelpulse2_exe_r_32.zip
    appveyor PushArtifact distrib_r_32.zip

    cd c:\projects\pixelpulse2\64\release
    C:\Qt\5.6\msvc2015_64\bin\windeployqt pixelpulse2.exe --qmldir ..\..\qml  --dir distrib
    cp C:\OpenSSL-Win64\libeay32.dll distrib
    cp C:\OpenSSL-Win64\libssl32.dll distrib
    cp C:\OpenSSL-Win64\ssleay32.dll distrib
    cp C:\OpenSSL-Win64\bin\msvcr120.dll distrib
    cp C:\libusb\x64\Release\dll\libusb-1.0.dll distrib
    7z a -y pixelpulse2_exe_r_64.zip pixelpulse2.exe
    7z a -y distrib_r_64.zip distrib

    appveyor PushArtifact pixelpulse2_exe_r_64.zip
    appveyor PushArtifact distrib_r_64.zip
