os: MinGW

platform:
 - x86

environment:
  QTDIR: C:\Qt\5.4\mingw491_32
  PATH: C:\Program Files (x86)\MSBuild\12.0\bin\;C:\mingw32\bin;%QTDIR%\bin;%PATH%

install:
  - ps: (new-object System.Net.WebClient).Downloadfile("https://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.1/threads-posix/dwarf/i686-4.9.1-release-posix-dwarf-rt_v3-rev0.7z", "c:\mingw.7z")
  - 7z x -y "c:\mingw.7z" -o"C:\"
  - ps: (new-object System.Net.WebClient).Downloadfile("https://downloads.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.19/libusb-1.0.19.7z", "c:\libusb.7z")
  - 7z x -y "c:\libusb.7z" -o"C:\libusb"

build_script:
  - git submodule update --init --recursive
  - qmake LIBS+="C:\libusb\MinGW32\static\libusb-1.0.a" INCLUDEPATH+="C:\libusb\include" pixelpulse2.pro
  - mingw32-make -j8
  - appveyor PushArtifact debug\pixelpulse2.exe -FileName pixelpulse2-debug.exe
  - appveyor PushArtifact release\pixelpulse2.exe
