os: unstable 

platform:
 - x86

install:
  - ps: (new-object System.Net.WebClient).Downloadfile("https://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-posix/dwarf/i686-4.9.2-release-posix-dwarf-rt_v3-rev0.7z", "c:\mingw.7z")
  - 7z x -y "c:\mingw.7z" -o"C:\" > nul
  - set QTDIR=C:\Qt\Qt5.3.2\5.3\mingw482_32
  - set PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;C:\mingw32\bin;%QTDIR%\bin;%PATH%
  - ps: (new-object System.Net.WebClient).Downloadfile("http://itdaniher.com/static/libusb-1.0-hp.7z", "c:\libusb.7z")
  - 7z x -y "c:\libusb.7z" -o"C:\libusb" > nul
  - ps: (new-object System.Net.WebClient).Downloadfile("http://curl.haxx.se/gknw.net/7.40.0/dist-w32/curl-7.40.0-devel-mingw32.zip", "c:\libcurl.zip")
  - 7z x -y "c:\libcurl.zip" -o"C:\libcurl" > nul
  - ps: (new-object System.Net.WebClient).Downloadfile("http://win-builds.org/1.5.0/packages/windows_32/jansson-2.6-1-i686-w64-mingw32.txz", "c:\libjansson.txz")
  - 7z x -y "c:\libjansson.txz" -o"C:\libjansson.tar" > nul
  - 7z x -y "c:\libjansson.tar" -o"C:\libjansson" > nul

build_script:
  - git submodule update --init --recursive
  - qmake LIBS+="C:\libusb\MinGW32\static\libusb-1.0.a" LIBS+="C:\libcurl\lib\libcurl.a" LIBS+="C:\libjansson\lib\libjansson.dll.a" INCLUDEPATH+="C:\libusb\include" INCLUDEPATH+="C:\libcurl\include" INCLUDEPATH+="C:\libjansson\include" pixelpulse2.pro
  - mingw32-make -j8
  - appveyor PushArtifact release\pixelpulse2.exe
