os: unstable

platform:
 - x86

# http://iweb.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.3/threads-posix/dwarf/i686-4.9.3-release-posix-dwarf-rt_v4-rev1.7z

install:
  - ps: (new-object System.Net.WebClient).Downloadfile("http://iweb.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/5.2.0/threads-posix/dwarf/i686-5.2.0-release-posix-dwarf-rt_v4-rev0.7z", "c:\mingw.7z")
  - 7z x -y "c:\mingw.7z" -o"C:\" > nul
  - ps: (new-object System.Net.WebClient).Downloadfile("http://sourceforge.net/projects/mingw-w64/files/External%20binary%20packages%20%28Win64%20hosted%29/MSYS%20%2832-bit%29/MSYS-20111123.zip", "c:\msys.zip")
  - 7z x -y "c:\msys.zip" -o"C:\" > nul
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - dir %QTDIR%\bin
  - '%QTDIR%\bin\qtenv2.bat'
  - set PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;C:\mingw32\bin;C:\msys\bin\;%QTDIR%\bin;%PATH%
  - ps: (new-object System.Net.WebClient).Downloadfile("http://itdaniher.com/static/libusb-1.0-hp.7z", "c:\libusb.7z")
  - 7z x -y "c:\libusb.7z" -o"C:\libusb" > nul
  - appveyor DownloadFile https://slproweb.com/download/Win32OpenSSL_Light-1_0_2d.exe
  - Win32OpenSSL_Light-1_0_2d.exe /silent /verysilent /sp- /suppressmsgboxes

build_script:
  - git submodule update --init --recursive
  - qmake pixelpulse2.pro
  - mingw32-make -j8

after_build:
- ps: |
    If (!(Test-Path -Path "distrib.zip")) {
      windeployqt --qmldir qml release\pixelpulse2.exe --dir distrib
      7z a -y distrib.zip distrib
    }
    appveyor PushArtifact release\pixelpulse2.exe
    appveyor PushArtifact distrib.zip

cache:
 - distrib.zip -> appveyor.yml
 - c:\mingw.7z -> appveyor.yml
 - c:\msys.zip -> appveyor.yml
